# Generated by Django 4.2.5 on 2023-09-11 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_trenermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trenermodel',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 9, 11, 16, 45, 52, 670373)),
        ),
    ]
